### ISSUE TITLE
package.js and package.json files

### ISSUE THREAD

**Issue by cedrikv** [stratease/dGrowl#4]
Hy, is it possible to add a package.js and package.json file? This would help prevent warnings when making a Dojo build. 
For reference:
https://github.com/SitePen/dgrid/blob/master/package.json
https://github.com/SitePen/dgrid/blob/master/package.js

**Comment by stratease** [comment]
If you're actively using this, feel free to contribute to it - I haven't had time to maintain or been using dojo actively in years now.
